### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by sward42**

### CODE REVIEW

**Comment by sward42** [comment]
I completed the quiz

**Comment by copypastedeveloper** [comment]
@sward42 , This is looking pretty good.  very terse.  The only thing you're missing is the validation that both inputs have a value before generating the tree.  Add that in and you're good to go.

**Comment by sward42** [comment]
I completed the quiz, with validation this time.

**Comment by copypastedeveloper** [comment]
👍  very nice.  merge it in.

**Pull request merged**
